import Head from "next/head";
import { useState } from "react";
import Cards from "./cards/Cards";

export default function Home() {
  const [currentPage, setCurrentPage] = useState("Home");
  const [cardsArray, setCardsArray] = useState([
    {
      id: "0",
      question: "What does the fox say?",
      answer: "Banana.",
      isBookmarked: true,
    },
    {
      id: "1",
      question: "To be or not to be?",
      answer: "To be.",
      isBookmarked: false,
    },
    {
      id: "2",
      question: "Cheeseburger oder Pommes?",
      answer: "Cheesepommes.",
      isBookmarked: true,
    },
    {
      id: "3",
      question: "Was ist der Sinn des Lebens?",
      answer: "Pommes.",
      isBookmarked: false,
    },
    {
      id: "4",
      question: "Welche Farbe hat eine Zitrone?",
      answer: "Gelb.",
      isBookmarked: false,
    },
  ]);

  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cards
        cards={Cards}
        currentPage={currentPage}
        setCurrentPage={setCurrentPage}
        cardsArray={cardsArray}
        setCardsArray={setCardsArray}
        key={cardsArray.id}
      />
    </>
  );
}
